semi: false
singleQuote: true
arrowParens: 'always'
requirePragma: false
trailingComma: 'none'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - <THIRD_PARTY_MODULES>
  - ^@/(.*)$
  - ^[./]
importOrderParserPlugins:
  - typescript
  - decorators-legacy
  - jsx
plugins:
  - '@trivago/prettier-plugin-sort-imports'
