CREATE TABLE `knex_migrations` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` integer, `migration_time` datetime);
CREATE TABLE `knex_migrations_lock` (`index` integer not null primary key autoincrement, `is_locked` integer);
CREATE TABLE `accounts` (`id` varchar(255), `email` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `passwordHash` varchar(255), `verificationCode` varchar(255), `verifiedAt` datetime default CURRENT_TIMESTAMP, `defaultActorId` varchar(255) null, `emailChangePending` varchar(255), `emailChangeCode` varchar(255), `emailChangeCodeExpiresAt` datetime, `emailVerifiedAt` datetime, `passwordResetCode` varchar(255), `passwordResetCodeExpiresAt` datetime, `name` varchar(255) null, `image` text null, `emailVerified` boolean default '0', `iconUrl` varchar(255) null, `role` text null default null, `twoFactorEnabled` boolean not null default '0', primary key (`id`));
CREATE UNIQUE INDEX `accounts_email_unique` on `accounts` (`email`);
CREATE INDEX `accountsIndex` on `accounts` (`email`, `createdAt`, `updatedAt`);
CREATE TABLE `follows` (`id` varchar(255), `actorId` varchar(255), `actorHost` varchar(255), `targetActorId` varchar(255), `targetActorHost` varchar(255), `status` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `inbox` varchar(255), `sharedInbox` varchar(255), `reblogs` boolean not null default '1', `notify` boolean not null default '0', `languages` text null, primary key (`id`));
CREATE INDEX `followsIndex` on `follows` (`actorId`, `actorHost`, `targetActorId`, `targetActorHost`, `status`, `createdAt`, `updatedAt`);
CREATE TABLE `attachments` (`id` varchar(255), `statusId` varchar(255), `url` varchar(255), `mediaType` varchar(255), `type` varchar(255), `width` integer, `height` integer, `name` text, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `actorId` varchar(255), `mediaId` varchar(255), primary key (`id`));
CREATE INDEX `attachmentsIndex` on `attachments` (`statusId`, `createdAt`, `updatedAt`);
CREATE TABLE `recipients` (`id` varchar(255), `statusId` varchar(255), `actorId` varchar(255), `type` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE TABLE `tags` (`id` varchar(255), `statusId` varchar(255), `type` varchar(255), `name` varchar(255), `value` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `nameNormalized` varchar(255), primary key (`id`));
CREATE TABLE IF NOT EXISTS "statuses" (`id` varchar(255), `actorId` varchar(255), `type` varchar(255), `reply` varchar(255), `createdAt` datetime DEFAULT CURRENT_TIMESTAMP, `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP, `content` text, `url` text null, `urlHash` varchar(64) null, `originalStatusId` varchar(255) null, `replyHash` varchar(64) null, PRIMARY KEY (`id`));
CREATE TABLE `likes` (`statusId` varchar(255), `actorId` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`statusId`, `actorId`));
CREATE TABLE `timelines` (`id` integer not null primary key autoincrement, `actorId` varchar(255), `timeline` varchar(255), `statusId` varchar(255), `statusActorId` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP);
CREATE TABLE `poll_choices` (`choiceId` integer not null primary key autoincrement, `statusId` varchar(255), `title` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `totalVotes` integer not null default '0');
CREATE TABLE `poll_answers` (`answerId` integer not null primary key autoincrement, `choice` integer not null, `actorId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `statusId` varchar(255) not null);
CREATE TABLE IF NOT EXISTS "account_providers" (`id` varchar(255), `accountId` varchar(255), `provider` varchar(255), `providerId` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `password` text null, `accessToken` text null, `refreshToken` text null, `idToken` text null, `accessTokenExpiresAt` datetime null, `refreshTokenExpiresAt` datetime null, `scope` text null, primary key (`id`));
CREATE TABLE `sessions` (`id` varchar(255), `accountId` varchar(255), `token` varchar(255), `expireAt` datetime, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `actorId` varchar(255) null, `ipAddress` text null, `userAgent` text null, primary key (`id`));
CREATE TABLE `status_history` (`id` integer not null primary key autoincrement, `statusId` varchar(255), `data` json, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP);
CREATE TABLE `medias` (`id` integer not null primary key autoincrement, `actorId` varchar(255), `original` varchar(255), `thumbnail` varchar(255) null, `description` varchar(255) null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `accountId` varchar(255), "originalMimeType" varchar(255), "originalBytes" bigint, `thumbnailBytes` bigint null, `thumbnailMimeType` varchar(255) null, `originalMetaData` json, `thumbnailMetaData` json null, `originalFileName` varchar(255) null, `focusX` float null, `focusY` float null);
CREATE UNIQUE INDEX `timelines_actorId_timeline_statusId_unique` on `timelines` (`actorId`, `timeline`, `statusId`);
CREATE INDEX `account_providers_accountId_provider_providerId_idx` on `account_providers` (`accountId`, `provider`, `providerId`);
CREATE INDEX `recipiences_statusId_type_idx` on `recipients` (`statusId`, `type`, `createdAt`, `updatedAt`);
CREATE INDEX `sessions_accountId_token_idx` on `sessions` (`accountId`, `token`);
CREATE INDEX `status_history_statusId_idx` on `status_history` (`statusId`, `createdAt`, `updatedAt`);
CREATE INDEX `statuses_actorId_idx` on `statuses` (`actorId`, `createdAt`, `updatedAt`);
CREATE INDEX `tags_statusId_type_idx` on `tags` (`statusId`, `type`, `createdAt`, `updatedAt`);
CREATE INDEX `medias_accountId_originalMimeType_idx` on `medias` (`accountId`, `originalMimeType`);
CREATE INDEX `medias_actorId_originalMimeType_idx` on `medias` (`actorId`, `originalMimeType`);
CREATE INDEX `verificationCodeIndex` on `accounts` (`verificationCode`);
CREATE INDEX `attachments_actorId_idx` on `attachments` (`actorId`);
CREATE TABLE IF NOT EXISTS "clients" (`id` varchar(255), "name" varchar(255), `secret` varchar(255), `redirectUris` text, `scopes` text, `website` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `applications_clientname_unique` on "clients" ("name");
CREATE TABLE `tokens` (`accessToken` varchar(255), `refreshToken` varchar(255) null, `accessTokenExpiresAt` datetime, `refreshTokenExpiresAt` datetime null, `clientId` varchar(255), `actorId` varchar(255), `accountId` varchar(255), `scopes` json, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`accessToken`));
CREATE TABLE `auth_codes` (`code` varchar(255), `redirectUri` varchar(255) null, `codeChallenge` varchar(255) null, `codeChallengeMethod` varchar(255) null, `clientId` varchar(255), `actorId` varchar(255), `accountId` varchar(255), `scopes` json, `expiresAt` datetime, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`code`));
CREATE INDEX `statusesReplyIndex` on `statuses` (`reply`);
CREATE TABLE IF NOT EXISTS "actors" (`id` varchar(255), `username` varchar(255), `accountId` varchar(255), `name` varchar(255), `summary` text, `publicKey` text, `privateKey` text, `createdAt` datetime DEFAULT CURRENT_TIMESTAMP, `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP, `settings` json, `domain` varchar(255), `deletionStatus` varchar(255) null, `deletionScheduledAt` datetime null, `type` varchar(255) not null default 'Person', FOREIGN KEY (`accountId`) REFERENCES `accounts` (`id`));
CREATE UNIQUE INDEX `actors_id_unique` on `actors` (`id`);
CREATE INDEX `actorsIndex` on `actors` (`username`, `createdAt`, `updatedAt`);
CREATE UNIQUE INDEX `actors_username_domain_unique` on `actors` (`username`, `domain`);
CREATE INDEX `recipientsTypeActorIdIndex` on `recipients` (`type`, `actorId`);
CREATE INDEX `timelinesActorIdTimelineCreatedAtIndex` on `timelines` (`actorId`, `timeline`, `createdAt`);
CREATE INDEX `timelinesStatusIdIndex` on `timelines` (`statusId`);
CREATE TABLE `notifications` (`id` varchar(255), `actorId` varchar(255) not null, `type` varchar(255) not null, `sourceActorId` varchar(255) not null, `statusId` varchar(255), `followId` varchar(255), `isRead` boolean default '0', `readAt` datetime, `groupKey` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `filtered` boolean not null default '0', primary key (`id`));
CREATE INDEX `notifications_actor_created` on `notifications` (`actorId`, `createdAt`);
CREATE INDEX `notifications_actor_unread` on `notifications` (`actorId`, `isRead`, `createdAt`);
CREATE INDEX `notifications_group_key` on `notifications` (`groupKey`, `createdAt`);
CREATE INDEX `notifications_follow_id` on `notifications` (`followId`);
CREATE INDEX `notifications_status_id` on `notifications` (`statusId`);
CREATE INDEX `poll_answers_statusid_actorid_index` on `poll_answers` (`statusId`, `actorId`);
CREATE TABLE `fitness_settings` (`id` varchar(255), `actorId` varchar(255) not null, `serviceType` varchar(255) not null, `clientId` varchar(255), `clientSecret` text, `webhookToken` varchar(255), `accessToken` text, `refreshToken` text, `tokenExpiresAt` datetime, `oauthState` varchar(255), `oauthStateExpiry` datetime, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `deletedAt` datetime, `privacyHomeLatitude` float, `privacyHomeLongitude` float, `privacyHideRadiusMeters` integer, `privacyLocations` json not null default '[]', `defaultVisibility` varchar(255), foreign key(`actorId`) references `actors`(`id`), primary key (`id`));
CREATE INDEX `fitness_settings_idx` on `fitness_settings` (`actorId`, `serviceType`, `deletedAt`);
CREATE INDEX `fitness_settings_webhook_token_idx` on `fitness_settings` (`webhookToken`);
CREATE UNIQUE INDEX "fitness_settings_unique_active" ON "fitness_settings" ("actorId", "serviceType") WHERE "deletedAt" IS NULL;
CREATE TABLE IF NOT EXISTS "counters" (`id` text, `value` bigint not null default '0', `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `bucketHour` datetime null default null, primary key (`id`));
CREATE INDEX `countersIndex` on `counters` (`id`, `createdAt`, `updatedAt`);
CREATE INDEX `statusesUrlHashIndex` on `statuses` (`urlHash`);
CREATE INDEX `actors_accountId_idx` on `actors` (`accountId`);
CREATE INDEX `medias_actorId_createdAt_idx` on `medias` (`actorId`, `createdAt`);
CREATE INDEX `attachments_mediaId_idx` on `attachments` (`mediaId`);
CREATE INDEX `recipients_type_actor_created_status_idx` on `recipients` (`type`, `actorId`, `createdAt`, `statusId`);
CREATE INDEX `passwordResetCodeIndex` on `accounts` (`passwordResetCode`);
CREATE TABLE `fitness_files` (`id` varchar(255), `actorId` varchar(255) not null, `statusId` varchar(255), `path` varchar(255) not null, `fileName` varchar(255) not null, `fileType` varchar(255) not null, `mimeType` varchar(255) not null, `bytes` bigint not null, `description` text, `hasMapData` boolean default '0', `mapImagePath` varchar(255), `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `deletedAt` datetime, `processingStatus` varchar(255) default 'pending', `totalDistanceMeters` float, `totalDurationSeconds` float, `elevationGainMeters` float, `activityType` varchar(255), `activityStartTime` datetime, `isPrimary` boolean not null default '1', `importBatchId` varchar(255), `importStatus` varchar(255), `importError` text, `deviceManufacturer` varchar(255), `deviceName` varchar(255), `sourceUrl` text, foreign key(`actorId`) references `actors`(`id`) on delete CASCADE, foreign key(`statusId`) references `statuses`(`id`) on delete SET NULL, primary key (`id`));
CREATE INDEX `fitness_files_actor_id_idx` on `fitness_files` (`actorId`);
CREATE INDEX `fitness_files_status_id_idx` on `fitness_files` (`statusId`);
CREATE INDEX `fitness_files_actor_created_idx` on `fitness_files` (`actorId`, `createdAt`);
CREATE INDEX `fitness_files_import_batch_id_idx` on `fitness_files` (`importBatchId`);
CREATE TABLE `strava_archive_imports` (`id` varchar(255), `actorId` varchar(255) not null, `archiveId` varchar(255) not null, `archiveFitnessFileId` varchar(255) not null, `batchId` varchar(255) not null, `visibility` varchar(255) not null, `status` varchar(255) not null, `nextActivityIndex` integer not null default '0', `pendingMediaActivities` text, `mediaAttachmentRetry` integer not null default '0', `totalActivitiesCount` integer, `completedActivitiesCount` integer not null default '0', `failedActivitiesCount` integer not null default '0', `firstFailureMessage` text, `lastError` text, `resolvedAt` datetime null, `createdAt` datetime not null default CURRENT_TIMESTAMP, `updatedAt` datetime not null default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `strava_archive_imports_archiveid_unique` on `strava_archive_imports` (`archiveId`);
CREATE INDEX `strava_archive_imports_actor_status_idx` on `strava_archive_imports` (`actorId`, `status`);
CREATE INDEX `strava_archive_imports_batch_id_idx` on `strava_archive_imports` (`batchId`);
CREATE UNIQUE INDEX strava_archive_imports_actor_active_idx ON strava_archive_imports("actorId") WHERE "resolvedAt" IS NULL;
CREATE TABLE `verification` (`id` text, `identifier` text not null, `value` text not null, `expiresAt` datetime not null, `createdAt` datetime not null default CURRENT_TIMESTAMP, `updatedAt` datetime not null default CURRENT_TIMESTAMP, primary key (`id`));
CREATE INDEX `verification_identifier_index` on `verification` (`identifier`);
CREATE TABLE `oauthClient` (`id` varchar(255), `clientId` varchar(255) not null, `clientSecret` text null, `disabled` boolean default '0', `skipConsent` boolean null, `enableEndSession` boolean null, `subjectType` varchar(255) null, `scopes` text null, `userId` varchar(255) null, `name` varchar(255) null, `uri` varchar(255) null, `icon` varchar(255) null, `contacts` text null, `tos` varchar(255) null, `policy` varchar(255) null, `softwareId` varchar(255) null, `softwareVersion` varchar(255) null, `softwareStatement` text null, `redirectUris` text not null, `postLogoutRedirectUris` text null, `tokenEndpointAuthMethod` varchar(255) null, `grantTypes` text null, `responseTypes` text null, `public` boolean null, `type` varchar(255) null, `requirePKCE` boolean null, `referenceId` varchar(255) null, `metadata` text null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, foreign key(`userId`) references `accounts`(`id`), primary key (`id`));
CREATE UNIQUE INDEX `oauthclient_clientid_unique` on `oauthClient` (`clientId`);
CREATE TABLE `oauthRefreshToken` (`id` varchar(255), `token` text not null, `clientId` varchar(255) not null, `sessionId` varchar(255) null, `userId` varchar(255) not null, `referenceId` varchar(255) null, `expiresAt` datetime not null, `revoked` datetime null, `authTime` datetime null, `scopes` text not null, `createdAt` datetime default CURRENT_TIMESTAMP, foreign key(`clientId`) references `oauthClient`(`clientId`), foreign key(`sessionId`) references `sessions`(`id`), foreign key(`userId`) references `accounts`(`id`), primary key (`id`));
CREATE UNIQUE INDEX `oauthrefreshtoken_token_unique` on `oauthRefreshToken` (`token`);
CREATE TABLE `oauthAccessToken` (`id` varchar(255), `token` text not null, `clientId` varchar(255) not null, `sessionId` varchar(255) null, `userId` varchar(255) null, `referenceId` varchar(255) null, `refreshId` varchar(255) null, `expiresAt` datetime not null, `scopes` text not null, `createdAt` datetime default CURRENT_TIMESTAMP, foreign key(`clientId`) references `oauthClient`(`clientId`), foreign key(`sessionId`) references `sessions`(`id`), foreign key(`userId`) references `accounts`(`id`), foreign key(`refreshId`) references `oauthRefreshToken`(`id`), primary key (`id`));
CREATE UNIQUE INDEX `oauthaccesstoken_token_unique` on `oauthAccessToken` (`token`);
CREATE TABLE `oauthConsent` (`id` varchar(255), `clientId` varchar(255) not null, `userId` varchar(255) null, `referenceId` varchar(255) null, `scopes` text not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, foreign key(`clientId`) references `oauthClient`(`clientId`), foreign key(`userId`) references `accounts`(`id`), primary key (`id`));
CREATE TABLE `jwks` (`id` varchar(255), `publicKey` text not null, `privateKey` text not null, `createdAt` datetime not null default CURRENT_TIMESTAMP, `expiresAt` datetime null, primary key (`id`));
CREATE TABLE `passkey` (`id` varchar(255), `name` varchar(255) null, `publicKey` text not null, `userId` varchar(255) not null, `credentialID` text not null, `counter` integer not null default '0', `deviceType` varchar(255) not null, `backedUp` boolean not null default '0', `transports` varchar(255) null, `aaguid` varchar(255) null, `createdAt` datetime not null default CURRENT_TIMESTAMP, foreign key(`userId`) references `accounts`(`id`) on delete CASCADE, primary key (`id`));
CREATE INDEX `passkey_userid_index` on `passkey` (`userId`);
CREATE UNIQUE INDEX `passkey_credentialid_unique` on `passkey` (`credentialID`);
CREATE INDEX `counters_bucket_hour_index` on `counters` (`bucketHour`);
CREATE INDEX `tags_nameNormalized_type_idx` on `tags` (`nameNormalized`, `type`);
CREATE TABLE `push_subscriptions` (`id` varchar(255), `actorId` varchar(255) not null, `endpoint` text not null, `p256dh` varchar(255) not null, `auth` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `alerts` text null, `policy` varchar(255) not null default 'all', `standard` boolean not null default '1', primary key (`id`));
CREATE INDEX `push_subscriptions_actor_idx` on `push_subscriptions` (`actorId`);
CREATE UNIQUE INDEX `push_subscriptions_endpoint_unique` on `push_subscriptions` (`endpoint`);
CREATE TABLE `twoFactor` (`id` varchar(255), `secret` text not null, `backupCodes` text not null, `userId` varchar(255) not null, `verified` boolean not null default '0', foreign key(`userId`) references `accounts`(`id`) on delete CASCADE, primary key (`id`));
CREATE UNIQUE INDEX `twofactor_userid_unique` on `twoFactor` (`userId`);
CREATE TABLE `domain_federation_rules` (`id` varchar(255), `domain` varchar(255) not null, `type` varchar(255) not null, `severity` varchar(255) null, `rejectMedia` boolean not null default '0', `rejectReports` boolean not null default '0', `privateComment` text null, `publicComment` text null, `obfuscate` boolean not null default '0', `source` varchar(255) null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `domain_federation_rules_type_domain_unique` on `domain_federation_rules` (`type`, `domain`);
CREATE INDEX `domain_federation_rules_type_idx` on `domain_federation_rules` (`type`, `createdAt`);
CREATE INDEX `domain_federation_rules_source_idx` on `domain_federation_rules` (`source`);
CREATE TABLE `poll_voters` (`id` integer not null primary key autoincrement, `statusId` varchar(255) not null, `actorId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX `poll_voters_statusid_actorid_unique` on `poll_voters` (`statusId`, `actorId`);
CREATE INDEX `poll_voters_statusid_index` on `poll_voters` (`statusId`);
CREATE INDEX `recipients_actorId_statusId_idx` on `recipients` (`actorId`, `statusId`);
CREATE INDEX `statuses_reply_type_idx` on `statuses` (`reply`, `type`);
CREATE TABLE `legacy_fitness_heatmap_media_cleanup` (`actorId` varchar(255) not null, `imagePath` varchar(255) not null, `createdAt` datetime not null, `deletedAt` datetime, `error` text, primary key (`actorId`, `imagePath`));
CREATE TABLE `fitness_route_heatmaps` (`id` varchar(255), `actorId` varchar(255) not null, `activityType` varchar(255), `activityTypeKey` varchar(255) not null default '', `periodType` varchar(255) not null, `periodKey` varchar(255) not null, `region` varchar(255) not null default '', `periodStart` datetime, `periodEnd` datetime, `bounds` text, `segments` text, `status` varchar(255) not null default 'pending', `error` text, `activityCount` integer not null default '0', `pointCount` integer not null default '0', `cursorOffset` integer not null default '0', `isPartial` boolean not null default '0', `createdAt` datetime not null, `updatedAt` datetime not null, `deletedAt` datetime, foreign key(`actorId`) references `actors`(`id`), primary key (`id`));
CREATE UNIQUE INDEX `fitness_route_heatmaps_actorid_activitytypekey_periodtype_periodkey_region_unique` on `fitness_route_heatmaps` (`actorId`, `activityTypeKey`, `periodType`, `periodKey`, `region`);
CREATE INDEX `fitness_route_heatmaps_actorid_status_index` on `fitness_route_heatmaps` (`actorId`, `status`);
CREATE INDEX `fitness_route_heatmaps_actorid_periodtype_index` on `fitness_route_heatmaps` (`actorId`, `periodType`);
CREATE TABLE `blocks` (`id` varchar(255), `actorId` varchar(255) not null, `actorHost` varchar(255) not null, `targetActorId` varchar(255) not null, `targetActorHost` varchar(255) not null, `uri` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `blocks_actor_target_unique` on `blocks` (`actorId`, `targetActorId`);
CREATE UNIQUE INDEX `blocks_uri_unique` on `blocks` (`uri`);
CREATE INDEX `blocks_actor_created` on `blocks` (`actorId`, `createdAt`);
CREATE INDEX `blocks_target` on `blocks` (`targetActorId`);
CREATE INDEX `oauth_client_reference_id_idx` on `oauthClient` (`referenceId`);
CREATE TABLE `bookmarks` (`id` integer not null primary key autoincrement, `actorId` varchar(255) not null, `statusId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, `sourceStatusId` varchar(255) null);
CREATE UNIQUE INDEX `bookmarks_actor_status_unique` on `bookmarks` (`actorId`, `statusId`);
CREATE INDEX `bookmarks_actor_created_id` on `bookmarks` (`actorId`, `createdAt`, `id`);
CREATE INDEX `bookmarks_status` on `bookmarks` (`statusId`);
CREATE INDEX `statuses_announce_actor_original_idx` on `statuses` (`type`, `actorId`, `originalStatusId`);
CREATE INDEX `bookmarks_actor_source_status` on `bookmarks` (`actorId`, `sourceStatusId`);
CREATE TABLE `direct_conversations` (`id` varchar(255), `rootStatusId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE INDEX `direct_conversations_root_status` on `direct_conversations` (`rootStatusId`);
CREATE TABLE `direct_conversation_participants` (`id` varchar(255), `conversationId` varchar(255) not null, `actorId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `direct_participant_conversation_actor` on `direct_conversation_participants` (`conversationId`, `actorId`);
CREATE INDEX `direct_participant_actor` on `direct_conversation_participants` (`actorId`);
CREATE TABLE `direct_conversation_statuses` (`conversationId` varchar(255) not null, `statusId` varchar(255) not null, `createdAt` datetime not null, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`conversationId`, `statusId`));
CREATE INDEX `direct_conversation_status` on `direct_conversation_statuses` (`statusId`);
CREATE INDEX `direct_conversation_statuses_order` on `direct_conversation_statuses` (`conversationId`, `createdAt`, `statusId`);
CREATE TABLE `direct_conversation_memberships` (`id` integer not null primary key autoincrement, `actorId` varchar(255) not null, `conversationId` varchar(255) not null, `lastStatusId` varchar(255) not null, `lastStatusCreatedAt` datetime not null, `unread` boolean not null default '0', `readAt` datetime null, `hiddenAt` datetime null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX `direct_membership_actor_conversation` on `direct_conversation_memberships` (`actorId`, `conversationId`);
CREATE INDEX `direct_membership_actor_visible` on `direct_conversation_memberships` (`actorId`, `hiddenAt`, `lastStatusCreatedAt`, `id`);
CREATE INDEX `direct_membership_last_status` on `direct_conversation_memberships` (`lastStatusId`);
CREATE INDEX `statusesReplyHashIndex` on `statuses` (`replyHash`);
CREATE TABLE `search_documents` (`id` varchar(320), `entityType` varchar(32) not null, `entityId` varchar(255) not null, `documentText` text not null, `actorId` varchar(255) null, `visibility` varchar(32) null, `entityCreatedAt` datetime null, `discoverable` boolean null, `postCount` integer null, `lastPostAt` datetime null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE INDEX `search_documents_entity_type_entity_id` on `search_documents` (`entityType`, `entityId`);
CREATE INDEX `search_documents_actor` on `search_documents` (`actorId`);
CREATE INDEX `search_documents_entity_created` on `search_documents` (`entityCreatedAt`);
CREATE INDEX `search_documents_post_count` on `search_documents` (`postCount`);
CREATE INDEX `search_documents_last_post` on `search_documents` (`lastPostAt`);
CREATE VIRTUAL TABLE search_documents_fts USING fts5(id UNINDEXED, documentText, content='search_documents', content_rowid='rowid')
/* search_documents_fts(id,documentText) */;
CREATE TRIGGER search_documents_ai AFTER INSERT ON search_documents BEGIN
        INSERT INTO search_documents_fts(rowid, id, documentText)
        VALUES (new.rowid, new.id, new.documentText);
      END;
CREATE TRIGGER search_documents_ad AFTER DELETE ON search_documents BEGIN
        INSERT INTO search_documents_fts(search_documents_fts, rowid, id, documentText)
        VALUES ('delete', old.rowid, old.id, old.documentText);
      END;
CREATE TRIGGER search_documents_au AFTER UPDATE ON search_documents BEGIN
        INSERT INTO search_documents_fts(search_documents_fts, rowid, id, documentText)
        VALUES ('delete', old.rowid, old.id, old.documentText);
        INSERT INTO search_documents_fts(rowid, id, documentText)
        VALUES (new.rowid, new.id, new.documentText);
      END;
CREATE TABLE `status_pins` (`actorId` varchar(255) not null, `statusId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, foreign key(`actorId`) references `actors`(`id`) on delete CASCADE, foreign key(`statusId`) references `statuses`(`id`) on delete CASCADE, primary key (`actorId`, `statusId`));
CREATE INDEX `status_pins_actor_created_status` on `status_pins` (`actorId`, `createdAt`, `statusId`);
CREATE INDEX `status_pins_status` on `status_pins` (`statusId`);
CREATE TABLE `mutes` (`id` varchar(255), `actorId` varchar(255) not null, `actorHost` varchar(255) not null, `targetActorId` varchar(255) not null, `targetActorHost` varchar(255) not null, `notifications` boolean not null default '1', `endsAt` bigint null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `mutes_actor_target_unique` on `mutes` (`actorId`, `targetActorId`);
CREATE INDEX `mutes_actor_created` on `mutes` (`actorId`, `createdAt`);
CREATE INDEX `mutes_target` on `mutes` (`targetActorId`);
CREATE TABLE `filters` (`id` varchar(255), `actorId` varchar(255) not null, `title` varchar(255) not null, `context` text not null, `filterAction` varchar(255) not null default 'warn', `expiresAt` bigint null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE INDEX `filters_actor_created` on `filters` (`actorId`, `createdAt`);
CREATE TABLE `filter_keywords` (`id` varchar(255), `filterId` varchar(255) not null, `keyword` text not null, `wholeWord` boolean not null default '0', `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `filter_keywords_filter_keyword_unique` on `filter_keywords` (`filterId`, `keyword`);
CREATE INDEX `filter_keywords_filter_id` on `filter_keywords` (`filterId`);
CREATE TABLE `filter_statuses` (`id` varchar(255), `filterId` varchar(255) not null, `statusId` text not null, `createdAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `filter_statuses_filter_status_unique` on `filter_statuses` (`filterId`, `statusId`);
CREATE INDEX `filter_statuses_filter_id` on `filter_statuses` (`filterId`);
CREATE INDEX `notifications_actor_filtered` on `notifications` (`actorId`, `filtered`, `createdAt`);
CREATE TABLE `markers` (`id` varchar(255), `actorId` varchar(255) not null, `timeline` varchar(255) not null, `lastReadId` text not null, `version` integer not null default '1', `updatedAt` datetime not null default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `markers_actor_timeline_unique` on `markers` (`actorId`, `timeline`);
CREATE TABLE `account_notes` (`id` varchar(255), `actorId` varchar(255) not null, `actorHost` varchar(255) not null, `targetActorId` varchar(255) not null, `targetActorHost` varchar(255) not null, `comment` text not null default '', `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `account_notes_actor_target_unique` on `account_notes` (`actorId`, `targetActorId`);
CREATE TABLE `lists` (`id` varchar(255), `actorId` varchar(255) not null, `title` varchar(255) not null, `repliesPolicy` varchar(255) not null default 'list', `exclusive` boolean not null default '0', `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE INDEX `lists_actor_created` on `lists` (`actorId`, `createdAt`);
CREATE TABLE `list_accounts` (`id` varchar(255), `listId` varchar(255) not null, `actorId` varchar(255) not null, `targetActorId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `list_accounts_list_target_unique` on `list_accounts` (`listId`, `targetActorId`);
CREATE INDEX `list_accounts_target` on `list_accounts` (`targetActorId`);
CREATE TABLE `status_mutes` (`actorId` varchar(255) not null, `statusId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`actorId`, `statusId`));
CREATE INDEX `status_mutes_status` on `status_mutes` (`statusId`);
CREATE TABLE `followed_tags` (`id` varchar(255), `actorId` varchar(255) not null, `name` varchar(255) not null, `nameNormalized` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `followed_tags_actor_name_unique` on `followed_tags` (`actorId`, `nameNormalized`);
CREATE INDEX `followed_tags_name` on `followed_tags` (`nameNormalized`);
CREATE TABLE `idempotency_keys` (`actorId` varchar(255) not null, `key` varchar(255) not null, `statusId` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, primary key (`actorId`, `key`));
CREATE INDEX `idempotency_keys_status` on `idempotency_keys` (`statusId`);
CREATE INDEX `idempotency_keys_created` on `idempotency_keys` (`createdAt`);
CREATE TABLE `reports` (`id` varchar(255), `actorId` varchar(255) not null, `targetActorId` varchar(255) not null, `category` varchar(255) not null default 'other', `comment` text not null default '', `forward` boolean not null default '0', `statusIds` text not null default '[]', `ruleIds` text not null default '[]', `actionTaken` boolean not null default '0', `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE INDEX `reports_actor_created` on `reports` (`actorId`, `createdAt`);
CREATE INDEX `reports_target` on `reports` (`targetActorId`);
CREATE TABLE `endorsements` (`id` integer not null primary key autoincrement, `actorId` varchar(255) not null, `actorHost` varchar(255) not null, `targetActorId` varchar(255) not null, `targetActorHost` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX `endorsements_actor_target_unique` on `endorsements` (`actorId`, `targetActorId`);
CREATE TABLE `customEmojis` (`id` varchar(255), `shortcode` varchar(255) not null, `url` text not null, `staticUrl` text not null, `category` varchar(255) null, `visibleInPicker` boolean not null default '1', `disabled` boolean not null default '0', `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `customemojis_shortcode_unique` on `customEmojis` (`shortcode`);
CREATE TABLE `featured_tags` (`id` varchar(255), `actorId` varchar(255) not null, `name` varchar(255) not null, `nameNormalized` varchar(255) not null, `createdAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `featured_tags_actor_name_unique` on `featured_tags` (`actorId`, `nameNormalized`);
CREATE INDEX `featured_tags_name` on `featured_tags` (`nameNormalized`);
CREATE TABLE `translation_cache` (`provider` varchar(191) not null, `sourceLanguage` varchar(16) not null, `targetLanguage` varchar(16) not null, `sourceHash` varchar(64) not null, `content` text not null, `detectedSourceLanguage` varchar(16), `createdAt` datetime default CURRENT_TIMESTAMP, primary key (`provider`, `sourceLanguage`, `targetLanguage`, `sourceHash`));
CREATE INDEX `translation_cache_created` on `translation_cache` (`createdAt`);
CREATE TABLE `server_filters` (`id` varchar(255), `title` varchar(255) not null, `context` text not null, `filterAction` varchar(255) not null default 'warn', `expiresAt` bigint null, `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE INDEX `server_filters_expires_at` on `server_filters` (`expiresAt`);
CREATE INDEX `server_filters_created` on `server_filters` (`createdAt`);
CREATE TABLE `server_filter_keywords` (`id` varchar(255), `filterId` varchar(255) not null, `keyword` text not null, `wholeWord` boolean not null default '0', `createdAt` datetime default CURRENT_TIMESTAMP, `updatedAt` datetime default CURRENT_TIMESTAMP, primary key (`id`));
CREATE UNIQUE INDEX `server_filter_keywords_filter_keyword_unique` on `server_filter_keywords` (`filterId`, `keyword`);
CREATE INDEX `server_filter_keywords_filter_id` on `server_filter_keywords` (`filterId`);
