// Parameter and result types of the notification domain (notifications, the
// requests queue for policy-filtered ones, and grouped lookups). The
// notification policy stays in lib/types/database/operations.ts.
// lib/types/database/operations.ts re-exports these, so existing imports keep
// working.
import { z } from 'zod'

export const NotificationType = z.enum([
  'follow_request',
  'follow',
  'like',
  'mention',
  'reply',
  'reblog',
  // Mastodon 4.5 quote posts: someone quoted the recipient's status.
  'quote',
  // A status the recipient quoted (an accepted quote edge) was edited by its
  // author. Mirrors the Mastodon push alert key of the same name.
  'quoted_update',
  // Someone reacted to the recipient's status with an emoji. Serialized as the
  // Pleroma dialect's `pleroma:emoji_reaction` (there is no core Mastodon type).
  'emoji_reaction',
  'activity_import',
  // A piece of fitness gear (or one of a bike's components) has passed the
  // distance the owner asked to be reminded at. Self-addressed: the recipient
  // is also the source actor, and it carries no status.
  'gear_service_due',
  // Mastodon 4.6 Collections: a member was added to a collection
  // (`added_to_collection`) or a collection they're in had its metadata changed
  // (`collection_update`).
  'added_to_collection',
  'collection_update'
])

export type NotificationType = z.infer<typeof NotificationType>

export interface Notification {
  id: string
  actorId: string
  type: NotificationType
  sourceActorId: string
  statusId?: string
  followId?: string
  isRead: boolean
  readAt?: number
  groupKey?: string
  // The emoji of an `emoji_reaction` notification (unicode, a local shortcode,
  // or `shortcode@domain`). Undefined for every other notification type.
  reactionName?: string
  // When true, the recipient's notification policy routed this notification to
  // the per-sender requests queue instead of the main timeline.
  filtered: boolean
  createdAt: number
  updatedAt: number
}

export type CreateNotificationParams = {
  actorId: string
  type: NotificationType
  sourceActorId: string
  statusId?: string
  followId?: string
  groupKey?: string
  // Only meaningful for `emoji_reaction`: the emoji that was used.
  reactionName?: string
  // Set true to route this notification to the per-sender requests queue
  // (computed by the notification policy). Defaults to false.
  filtered?: boolean
}

export type GetNotificationsParams = {
  actorId: string
  limit: number
  offset?: number
  // Restrict to notifications generated by this source actor (full actor
  // URL) — backs the Mastodon `account_id` query parameter.
  sourceActorId?: string
  types?: NotificationType[]
  excludeTypes?: NotificationType[]
  onlyUnread?: boolean
  ids?: string[]
  maxNotificationId?: string
  minNotificationId?: string
  sinceNotificationId?: string
  // When omitted/false, policy-filtered notifications (filtered = true) are
  // excluded. Pass true to include them (Mastodon `include_filtered`).
  includeFiltered?: boolean
}

export type GetNotificationsCountParams = {
  actorId: string
  onlyUnread?: boolean
  types?: NotificationType[]
  excludeTypes?: NotificationType[]
  // Cap the count at this many notifications (Mastodon `unread_count` caps at
  // 100 by default, max 1000). When omitted, counts all matching rows.
  limit?: number
  includeFiltered?: boolean
  // Count only policy-filtered notifications (overrides includeFiltered). Used
  // for the notification policy summary's pending_notifications_count.
  filteredOnly?: boolean
}

export type MarkNotificationsReadParams = {
  notificationIds: string[]
}

// A grouped, per-source-actor view of policy-filtered notifications — the
// backing data for Mastodon's NotificationRequest entity.
export interface NotificationRequest {
  // The source actor id (full URL) the filtered notifications came from.
  sourceActorId: string
  notificationsCount: number
  // The most recent filtered notification from this source actor.
  lastNotification: Notification
  createdAt: number
  updatedAt: number
}

export type GetNotificationRequestsParams = {
  actorId: string
  limit: number
  offset?: number
  maxCursor?: { updatedAt: number; sourceActorId: string }
  sinceCursor?: { updatedAt: number; sourceActorId: string }
}

export type GetNotificationRequestParams = {
  actorId: string
  sourceActorId: string
}

export type ResolveNotificationRequestsParams = {
  actorId: string
  sourceActorIds: string[]
}

export type NotificationGroupKeyParams = {
  actorId: string
  // A shared groupKey, or (for ungrouped notifications) a notification id.
  groupKey: string
  includeFiltered?: boolean
  // Newest-first row cap for getNotificationsForGroupKey, clamped to the
  // database's hard maximum (1000); ignored by dismissNotificationGroup.
  limit?: number
}

export interface NotificationDatabase {
  createNotification(params: CreateNotificationParams): Promise<Notification>
  getNotifications(params: GetNotificationsParams): Promise<Notification[]>
  getNotificationsCount(params: GetNotificationsCountParams): Promise<number>
  markNotificationsRead(params: MarkNotificationsReadParams): Promise<void>
  deleteNotification(notificationId: string): Promise<void>

  // Notification requests: grouped views over filtered = true notifications.
  getNotificationRequests(
    params: GetNotificationRequestsParams
  ): Promise<NotificationRequest[]>
  getNotificationRequest(
    params: GetNotificationRequestParams
  ): Promise<NotificationRequest | null>
  getNotificationRequestsCount(params: { actorId: string }): Promise<number>
  // Accept = clear the filtered flag so the notifications surface in the main
  // timeline. Dismiss = delete the filtered notifications.
  acceptNotificationRequests(
    params: ResolveNotificationRequestsParams
  ): Promise<void>
  dismissNotificationRequests(
    params: ResolveNotificationRequestsParams
  ): Promise<void>

  // Grouped notifications (v2): resolve and dismiss by group key (or, for
  // ungrouped notifications, by notification id).
  getNotificationsForGroupKey(
    params: NotificationGroupKeyParams
  ): Promise<Notification[]>
  dismissNotificationGroup(params: NotificationGroupKeyParams): Promise<void>
}
