export const CREATE_ANNOUNCE_JOB_NAME = 'CreateAnnounceJob'
export const CREATE_NOTE_JOB_NAME = 'CreateNoteJob'
export const CREATE_POLL_JOB_NAME = 'CreatePollJob'
export const UPDATE_NOTE_JOB_NAME = 'UpdateNoteJob'
export const UPDATE_POLL_JOB_NAME = 'UpdatePollJob'
