// Re-export from new location for backward compatibility
export {
  AccountDatabase,
  IsAccountExistsParams,
  IsUsernameExistsParams,
  CreateAccountParams,
  GetAccountFromIdParams,
  GetAccountFromEmailParams,
  GetAccountFromProviderIdParams,
  LinkAccountWithProviderParams,
  VerifyAccountParams,
  CreateAccountSessionParams,
  GetAccountSessionParams,
  GetAccountAllSessionsParams,
  DeleteAccountSessionParams,
  UpdateAccountSessionParams,
  GetAccountProvidersParams,
  UnlinkAccountFromProviderParams,
  CreateActorForAccountParams,
  GetActorsForAccountParams,
  SetDefaultActorParams,
  SetSessionActorParams,
  RequestEmailChangeParams,
  VerifyEmailChangeParams,
  ChangePasswordParams
} from '@/lib/types/database/operations'
